export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const API_KEY = 'user_80CtuhuL9K2DLvDN8Cp7x'
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
// export const FETCH_GUESTS_SUCCESS = 'FETCH_GUESTS_SUCCESS'; 
// export const FETCH_GUESTS_FAILURE = 'FETCH_GUESTS_FAILURE';
